[package]
name = "kvs"
version = "0.3.0"
authors = ["Carter Green <cartergr@usc.edu>"]
edition = "2018"

[dependencies]
bincode = "1.2.1"
serde = { features = ["derive"], version = "1.0" }

[dev-dependencies]
criterion = "0.2.11"
tempfile = "3.0.7"
walkdir = "2.2.7"
