[package]
name = "kvs-client"
version = "0.3.0"
authors = ["Carter Green <cartergr@usc.edu>"]
edition = "2018"

[dependencies]
clap = "2.33"
kvs = { path = "../core" }
bincode = "1.2.1"

[dev-dependencies]
assert_cmd = "0.11"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
